name = "FileTracer"
version = "0.1.0"
defaultTargets = ["filetracer"]

[[lean_lib]]
name = "FileTracer"

[[lean_exe]]
name = "filetracer"
root = "Main"

[[require]]
name = "Lean4MyLib"
git = "https://github.com/shinamon610/Lean4MyLib"
rev = "main"